Controllers/SignUpController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Acme_Ecommerce.Models;
using Acme_Database_Utility;

namespace Acme_Ecommerce.Controllers
{
    public class SignUpController : Controller
    {
        // GET: SignUp
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(UserModel user)
        {
            DatabaseUtil util = new DatabaseUtil();
            bool inserted = util.Insert(user);

            if (inserted)
            {
                return RedirectToAction("Index", "Login");
            }
            else
            {
                ViewBag.Message = "User could not be inserted";
                ViewBag.Bool = false;
                return View();
            }

           
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/lib/font-awesome/css/all.css" rel="stylesheet" />
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#"><img class="logo" src="~/Assets/App Images/ACME_logo.png"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    @Html.ActionLink("Home", "Index", "Home", new { area = " " }, new { @class = "nav-link" })
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" href="#">Departments</a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        @Html.ActionLink("Technology", "SearchByDepartment", "Home", new { type = "Tech" }, new { @class = "dropdown-item" })
                        <div class="dropdown-divider"></div>
                        @Html.ActionLink("Books", "SearchByDepartment", "Home", new { type = "Book" }, new { @class = "dropdown-item" })
                        <div class="dropdown-divider"></div>
                        @Html.ActionLink("Cosmetics", "SearchByDepartment", "Home", new { type = "Cosmetic" }, new { @class = "dropdown-item" })
                        <div class="dropdown-divider"></div>
                        @Html.ActionLink("Others", "SearchByDepartment", "Home", new { type = "Other" }, new { @class = "dropdown-item" })
                    </div>
                </li>
                @if (Convert.ToBoolean(Session["isAdmin"]) == true)
                {
                    <li class="nav-item">
                        @Html.ActionLink("Orders", "AdminPage", "Home", new { area = " " }, new { @class = "nav-link" })
                    </li>
                }
                @if (Convert.ToBoolean(Session["isLoggedIn"]) == true)
                {
                <li class="nav-item">
                    @Html.ActionLink("Profile", "OrderHistory", "Home", new { area = " " }, new { @class = "nav-link" })
                </li>
                }

            </ul>
        </div>
        <div class="authorization-menu">


            @if (Convert.ToBoolean(Session["isLoggedIn"]) == false)
            {
                @Html.ActionLink("Login", "Index", "Login", new { area = " " }, new { @class = "btn btn-outline-primary" })
                @Html.ActionLink("Sign Up", "Index", "SignUp", new { area = " " }, new { @class = "btn btn-outline-primary" })
            }
        </div>

        <div class="cart-icon">
            <a style="text-decoration:none; color: #333;" class="icon" href="@Url.Action("Checkout","Home")"><i class="fas fa-shopping-cart icon"></i></a>           
        </div>
        <div class="wish-list-icon">
            <i class="fas fa-heart"></i>
        </div>
    </nav>
@*

    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>*@
    <div>
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script>
        $(".carousel").carousel({
            interval: 1000,
        });
    </script>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>